"""
Словарь автомобильных брендов: китайский → английский.
Используется переводчиком ПЕРЕД обращением к Google Translate.
Если бренд найден в словаре — перевод берётся отсюда.
"""

# Китайское название → правильное английское название
BRAND_NAMES: dict[str, str] = {
    # Немецкие
    "大众": "Volkswagen",
    "宝马": "BMW",
    "奔驰": "Mercedes-Benz",
    "奥迪": "Audi",
    "保时捷": "Porsche",
    "迈巴赫": "Maybach",
    "欧宝": "Opel",
    "斯柯达": "Skoda",
    "西雅特": "SEAT",
    # Японские
    "丰田": "Toyota",
    "本田": "Honda",
    "日产": "Nissan",
    "马自达": "Mazda",
    "三菱": "Mitsubishi",
    "铃木": "Suzuki",
    "斯巴鲁": "Subaru",
    "雷克萨斯": "Lexus",
    "英菲尼迪": "Infiniti",
    "讴歌": "Acura",
    "大发": "Daihatsu",
    "五十铃": "Isuzu",
    "光冈": "Mitsuoka",
    # Корейские
    "现代": "Hyundai",
    "起亚": "Kia",
    "双龙": "SsangYong",
    "捷尼赛思": "Genesis",
    # Американские
    "福特": "Ford",
    "雪佛兰": "Chevrolet",
    "别克": "Buick",
    "凯迪拉克": "Cadillac",
    "林肯": "Lincoln",
    "道奇": "Dodge",
    "克莱斯勒": "Chrysler",
    "悍马": "Hummer",
    "特斯拉": "Tesla",
    "捷达": "Jetta",
    # Итальянские
    "菲亚特": "Fiat",
    "法拉利": "Ferrari",
    "兰博基尼": "Lamborghini",
    "玛莎拉蒂": "Maserati",
    "阿尔法·罗密欧": "Alfa Romeo",
    "帕加尼": "Pagani",
    "布加迪": "Bugatti",
    "依维柯": "Iveco",
    # Британские
    "捷豹": "Jaguar",
    "路虎": "Land Rover",
    "宾利": "Bentley",
    "劳斯莱斯": "Rolls-Royce",
    "阿斯顿·马丁": "Aston Martin",
    "迈凯伦": "McLaren",
    "莲花跑车": "Lotus",
    "莲花汽车": "Lotus",
    "摩根": "Morgan",
    "英力士掷弹兵": "INEOS Grenadier",
    # Французские
    "标致": "Peugeot",
    "雷诺": "Renault",
    "雪铁龙": "Citroën",
    # Шведские
    "沃尔沃": "Volvo",
    "萨博": "Saab",
    "科尼赛克": "Koenigsegg",
    # Китайские — крупные
    "比亚迪": "BYD",
    "吉利汽车": "Geely",
    "吉利几何": "Geometry",
    "吉利银河": "Galaxy",
    "吉利雷达": "Radar",
    "长城": "Great Wall",
    "哈弗": "Haval",
    "魏牌": "WEY",
    "坦克": "Tank",
    "长安": "Changan",
    "长安欧尚": "Changan Oshan",
    "长安凯程": "Changan Kaicheng",
    "长安跨越": "Changan Kuayue",
    "长安启源": "Changan Qiyuan",
    "奇瑞": "Chery",
    "奇瑞新能源": "Chery New Energy",
    "奇瑞风云": "Chery Fengyun",
    "荣威": "Roewe",
    "名爵": "MG",
    "红旗": "Hongqi",
    "蔚来": "NIO",
    "小鹏": "Xpeng",
    "理想汽车": "Li Auto",
    "极氪": "Zeekr",
    "零跑汽车": "Leapmotor",
    "哪吒汽车": "Neta",
    "埃安": "AION",
    "深蓝汽车": "Deepal",
    "阿维塔": "Avatr",
    "智己汽车": "IM Motors",
    "高合汽车": "HiPhi",
    "岚图汽车": "Voyah",
    "仰望": "Yangwang",
    "方程豹": "Fang Cheng Bao",
    "极越": "Jiyue",
    "猛士": "Mengshi",
    "小米汽车": "Xiaomi",
    "鸿蒙智行": "AITO",
    "问界": "AITO",
    "智界": "Maextro",
    "享界": "Luxeed",
    "尊界": "Stelato",
    "乐道": "ONVO",
    "星途": "Exeed",
    "捷途": "Jetour",
    "捷途山海": "Jetour Shanhai",
    "捷途纵横": "Jetour Zongheng",
    "领克": "Lynk & Co",
    "腾势": "Denza",
    "思皓": "Sehol",
    "欧拉": "ORA",
    "蓝电": "Blue E",
    # Китайские — средние/малые
    "中华": "Brilliance",
    "北京越野": "Beijing Off-Road",
    "北京汽车": "BAIC",
    "北汽新能源": "BAIC New Energy",
    "北汽昌河": "BAIC Changhe",
    "北汽威旺": "BAIC Weiwang",
    "北汽幻速": "BAIC Huansu",
    "北汽道达": "BAIC Daoda",
    "北汽瑞翔": "BAIC Ruixiang",
    "北汽泰普": "BAIC Taipu",
    "东风": "Dongfeng",
    "东风风神": "Dongfeng Aeolus",
    "东风风行": "Dongfeng Fengxing",
    "东风风光": "Dongfeng Fengguang",
    "东风风度": "Dongfeng Fengdu",
    "东风小康": "Dongfeng Xiaokang",
    "东风富康": "Dongfeng Fukang",
    "东风御风": "Dongfeng Yufeng",
    "东风奕派": "Dongfeng Yipai",
    "东南": "Soueast",
    "广汽传祺": "GAC Trumpchi",
    "广汽集团": "GAC Group",
    "广汽吉奥": "GAC Gonow",
    "广汽昊铂": "GAC Hyper",
    "江汽集团": "JAC",
    "江淮汽车": "JAC Motors",
    "江淮瑞风": "JAC Refine",
    "江淮钇为": "JAC Yiwei",
    "江铃": "JMC",
    "江铃集团新能源": "JMC New Energy",
    "江铃晶马汽车": "JMC Jingma",
    "一汽": "FAW",
    "一汽凌河": "FAW Linghe",
    "五菱汽车": "Wuling",
    "宝骏": "Baojun",
    "启辰": "Venucia",
    "海马": "Haima",
    "金杯": "Jinbei",
    "金龙": "King Long",
    "金龙礼宾": "King Long",
    "黄海": "Huanghai",
    "猎豹汽车": "Leopaard",
    "安徽猎豹": "Leopaard",
    "陆风": "Landwind",
    "华泰": "Hawtai",
    "华泰新能源": "Hawtai New Energy",
    "众泰": "Zotye",
    "奔腾": "Besturn",
    "福田": "Foton",
    "力帆汽车": "Lifan",
    "哈飞": "Hafei",
    "华普": "SMA",
    "观致": "Qoros",
    "大通": "Maxus",
    "纳智捷": "Luxgen",
    "威马汽车": "WM Motor",
    "合创汽车": "Hycan",
    "天际汽车": "Enovate",
    "恒驰": "Hengchi",
    "创维汽车": "Skyworth Auto",
    "大运": "Dayun",
    "远程": "Farizon",
    "九龙": "Joylong",
    "凯马": "Kaima",
    "中兴": "Zhongxing",
    "双环": "Shuanghuan",
    "飞碟汽车": "Feidie",
    "野马汽车": "Yema",
    "野马新能源": "Yema New Energy",
    "朋克汽车": "Punk Auto",
    "红星汽车": "Red Star",
    "中国重汽": "SINOTRUK",
    "中国重汽VGV": "SINOTRUK VGV",
    "宇通客车": "Yutong",
    "宇通房车": "Yutong RV",
    "中通客车": "Zhongtong",
    "上汽跃进": "SAIC Yuejin",
    "灵悉": "Lingxi",
    "神州": "Shenzhou",
    # Тюнинг / Специальные
    "赛麟": "Saleen",
    "卡尔森": "Carlsson",
    "世爵": "Spyker",
    "威兹曼": "Wiesmann",
    "乔治·巴顿": "George Patton",
    "曹操汽车": "CaoCao",
    "货拉拉多拉汽车": "Lalamove Dora",
    # AITO бренды
    "AITO 问界": "AITO",
    "SERES赛力斯": "SERES",
    "Polestar极星": "Polestar",
    "ARCFOX极狐": "ARCFOX",
    "ROX极石": "ROX",
    "firefly萤火虫": "Firefly",
    "奥迪AUDI": "Audi",
    "QQ新能源": "QQ New Energy",
}
